/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tp.pkgfinal;
import java.sql.*;
import java.awt.*;
import javax.swing.*;
/**
 *
 * @author 200666155
 */
public class AppLocale extends javax.swing.JFrame {

    /**
     * Creates new form AppLocale
     */
    public AppLocale(ConnectionOracle conn) {
      initComponents();
      this.connBD = conn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTN_AjouterArme = new javax.swing.JButton();
        BTN_AjouterArmure = new javax.swing.JButton();
        BTN_AjouterPotion = new javax.swing.JButton();
        BTN_AjouterHabilite = new javax.swing.JButton();
        BTN_ConsulUsager = new javax.swing.JButton();
        BTN_Inventaire = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        BTN_AjouterArme.setText("Ajouter Arme");
        BTN_AjouterArme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AjouterArmeActionPerformed(evt);
            }
        });

        BTN_AjouterArmure.setText("Ajouter Armure");
        BTN_AjouterArmure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AjouterArmureActionPerformed(evt);
            }
        });

        BTN_AjouterPotion.setText("Ajouter Potion");
        BTN_AjouterPotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AjouterPotionActionPerformed(evt);
            }
        });

        BTN_AjouterHabilite.setText("Ajouter Habilité");
        BTN_AjouterHabilite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AjouterHabiliteActionPerformed(evt);
            }
        });

        BTN_ConsulUsager.setText("Consulter Usager");
        BTN_ConsulUsager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ConsulUsagerActionPerformed(evt);
            }
        });

        BTN_Inventaire.setText("Consulter Inventaire");
        BTN_Inventaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_InventaireActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTN_ConsulUsager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTN_AjouterHabilite, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(BTN_AjouterPotion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTN_AjouterArmure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTN_AjouterArme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52)
                .addComponent(BTN_Inventaire)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_AjouterArme)
                    .addComponent(BTN_Inventaire))
                .addGap(18, 18, 18)
                .addComponent(BTN_AjouterArmure)
                .addGap(18, 18, 18)
                .addComponent(BTN_AjouterPotion)
                .addGap(26, 26, 26)
                .addComponent(BTN_AjouterHabilite)
                .addGap(18, 18, 18)
                .addComponent(BTN_ConsulUsager)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_AjouterArmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AjouterArmeActionPerformed
        // TODO add your handling code here:
        new Arme(connBD).setVisible(true);
    }//GEN-LAST:event_BTN_AjouterArmeActionPerformed

    private void BTN_AjouterArmureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AjouterArmureActionPerformed
        // TODO add your handling code here:
        new Armure(connBD).setVisible(true);
    }//GEN-LAST:event_BTN_AjouterArmureActionPerformed

    private void BTN_AjouterPotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AjouterPotionActionPerformed
        // TODO add your handling code here:
        new Potion(connBD).setVisible(true);
    }//GEN-LAST:event_BTN_AjouterPotionActionPerformed

    private void BTN_AjouterHabiliteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AjouterHabiliteActionPerformed
        // TODO add your handling code here:
        new Habilitées(connBD).setVisible(true);
    }//GEN-LAST:event_BTN_AjouterHabiliteActionPerformed

    private void BTN_ConsulUsagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ConsulUsagerActionPerformed
        // TODO add your handling code here:
        new Joueurs(connBD).setVisible(true);
    }//GEN-LAST:event_BTN_ConsulUsagerActionPerformed

    private void BTN_InventaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_InventaireActionPerformed
        // TODO add your handling code here:
        new Inventaire(connBD).setVisible(true);
    }//GEN-LAST:event_BTN_InventaireActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppLocale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppLocale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppLocale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppLocale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AppLocale().setVisible(true);
            }
        });
    }
// Declaration d'une variable connBD de type ConnectionOracle
   private ConnectionOracle connBD;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_AjouterArme;
    private javax.swing.JButton BTN_AjouterArmure;
    private javax.swing.JButton BTN_AjouterHabilite;
    private javax.swing.JButton BTN_AjouterPotion;
    private javax.swing.JButton BTN_ConsulUsager;
    private javax.swing.JButton BTN_Inventaire;
    // End of variables declaration//GEN-END:variables
}
