/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/

package tp.pkgfinal;
import java.sql.*;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author 200666155
 */
public class Arme extends javax.swing.JFrame {
    
    /**
     * Creates new form Arme
     */
    public Arme(ConnectionOracle conn) {
        initComponents();
        this.connBD = conn;
        BTN_Premier.doClick();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TB_ID = new javax.swing.JTextField();
        TB_NomItem = new javax.swing.JTextField();
        TB_Prix = new javax.swing.JTextField();
        TB_Quantite = new javax.swing.JTextField();
        TB_Efficacite = new javax.swing.JTextField();
        TB_Degats = new javax.swing.JTextField();
        BTN_Ajouter = new javax.swing.JButton();
        BTN_Modifier = new javax.swing.JButton();
        BTN_Supprimer = new javax.swing.JButton();
        L_Genre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BTN_Premier = new javax.swing.JButton();
        BTN_Precedent = new javax.swing.JButton();
        BTN_Suivant = new javax.swing.JButton();
        BTN_Dernier = new javax.swing.JButton();
        BTN_OK = new javax.swing.JButton();
        BTN_Vider = new javax.swing.JButton();
        CHK_Dispo = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TB_ID.setEnabled(false);

        BTN_Ajouter.setText("Ajouter");
        BTN_Ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AjouterActionPerformed(evt);
            }
        });

        BTN_Modifier.setText("Modifier");
        BTN_Modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ModifierActionPerformed(evt);
            }
        });

        BTN_Supprimer.setText("Supprimer");
        BTN_Supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SupprimerActionPerformed(evt);
            }
        });

        L_Genre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        L_Genre.setText("Armes");

        jLabel2.setText("IDItem");

        jLabel3.setText("Nom Item");

        jLabel4.setText("Prix");

        jLabel5.setText("Quantité Dispo");

        jLabel6.setText("Efficacité");

        jLabel7.setText("Degats");

        BTN_Premier.setText("<<");
        BTN_Premier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_PremierActionPerformed(evt);
            }
        });

        BTN_Precedent.setText("Précédent");
        BTN_Precedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_PrecedentActionPerformed(evt);
            }
        });

        BTN_Suivant.setText("Suivant");
        BTN_Suivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SuivantActionPerformed(evt);
            }
        });

        BTN_Dernier.setText(">>");
        BTN_Dernier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_DernierActionPerformed(evt);
            }
        });

        BTN_OK.setText("OK");
        BTN_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_OKActionPerformed(evt);
            }
        });

        BTN_Vider.setText("Vider");
        BTN_Vider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ViderActionPerformed(evt);
            }
        });

        CHK_Dispo.setText("Disponible");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(L_Genre))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CHK_Dispo)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TB_Quantite)
                                .addComponent(TB_Prix)
                                .addComponent(TB_NomItem)
                                .addComponent(TB_ID)
                                .addComponent(TB_Degats, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                .addComponent(TB_Efficacite)
                                .addComponent(BTN_Vider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTN_Ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTN_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BTN_Modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BTN_Supprimer))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTN_Premier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTN_Precedent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTN_Suivant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTN_Dernier)))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(L_Genre)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TB_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TB_NomItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TB_Prix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TB_Quantite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TB_Efficacite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TB_Degats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CHK_Dispo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(BTN_Vider)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_Premier)
                    .addComponent(BTN_Precedent)
                    .addComponent(BTN_Suivant)
                    .addComponent(BTN_Dernier))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_Ajouter)
                    .addComponent(BTN_Modifier)
                    .addComponent(BTN_Supprimer))
                .addGap(23, 23, 23)
                .addComponent(BTN_OK)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void BTN_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_OKActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BTN_OKActionPerformed
    
    private void BTN_AjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AjouterActionPerformed
        String nomItem = TB_NomItem.getText();
        String genre = L_Genre.getText();
        double prix = Double.parseDouble(TB_Prix.getText());
        int quantite = Integer.parseInt(TB_Quantite.getText());
        int efficacite = Integer.parseInt(TB_Efficacite.getText());
        int degats = Integer.parseInt(TB_Degats.getText());
        int disponible=0;
        if(CHK_Dispo.isSelected())
        {
            disponible = 1;
        }
        
        try
        {
            CallableStatement stminsertArmes = connBD.getConnection().prepareCall("{ call GESTIONARMES.INSERTION(?,?,?,?,?,?,?)}");
            
            stminsertArmes.setString(1, nomItem);
            stminsertArmes.setString(2, genre);
            stminsertArmes.setDouble(3, prix);
            stminsertArmes.setInt(4, quantite);
            stminsertArmes.setInt(5, disponible);
            stminsertArmes.setInt(6, efficacite);
            stminsertArmes.setInt(7, degats);
            stminsertArmes.executeUpdate();
            BTN_Premier.doClick();
        }
        
        catch(SQLException se){System.out.println("err" + se);}
    }//GEN-LAST:event_BTN_AjouterActionPerformed
    
    private void BTN_ModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ModifierActionPerformed
        //String sqlupdateArmes ="update Armes set efficacite = ?,degats= ? where IDITEM = " + TB_ID.getText();
        //String sqlupdateItems = "update Items set nomItem = ? ,genre=?, prix = ? , quantitedispo = ? where IDITEM = " + TB_ID.getText();
        
        int iditem = Integer.parseInt(TB_ID.getText());
        String nomItem = TB_NomItem.getText();
        String genre = L_Genre.getText();
        double prix = Double.parseDouble(TB_Prix.getText());
        int quantite = Integer.parseInt(TB_Quantite.getText());
        int efficacite = Integer.parseInt(TB_Efficacite.getText());
        int degats = Integer.parseInt(TB_Degats.getText());
        int disponible=0;
        if(CHK_Dispo.isSelected())
        {
            disponible = 1;
        }
        
        try
        {
            //PreparedStatement stmupdateArmes= connBD.getConnection().prepareStatement(sqlupdateArmes);
            //PreparedStatement stmupdateItems= connBD.getConnection().prepareStatement(sqlupdateItems);
            CallableStatement stmupdateItems =connBD.getConnection().prepareCall("{ call GESTIONARMES.MODIFIER(?,?,?,?,?,?,?,?)}");
            
            stmupdateItems.setInt(1,iditem);
            stmupdateItems.setString(2, nomItem);
            stmupdateItems.setString(3, genre);
            stmupdateItems.setDouble(4, prix);
            stmupdateItems.setInt(5, quantite);
            stmupdateItems.setInt(6, disponible);
            stmupdateItems.setInt(7, efficacite);
            stmupdateItems.setInt(8, degats);
            stmupdateItems.executeUpdate();
            BTN_Premier.doClick();
        }
        
        catch(SQLException se){System.out.println("err" + se);}
    }//GEN-LAST:event_BTN_ModifierActionPerformed
    
    private void BTN_SupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SupprimerActionPerformed
        // TODO add your handling code here:
        String sqlDeleteArmes = "DELETE FROM ARMES WHERE IDITEM = "+TB_ID.getText();
        String sqlDeleteItems = "DELETE FROM ITEMS WHERE IDITEM = "+TB_ID.getText();
        
        
        try
        {
            Statement stmDelete = connBD.getConnection().createStatement();
            stmDelete.executeQuery(sqlDeleteArmes);
            stmDelete.executeQuery(sqlDeleteItems);
            BTN_Premier.doClick();
        }
        catch(SQLException se)
        {
            System.out.println("err" + se);
        }
    }//GEN-LAST:event_BTN_SupprimerActionPerformed
    
    private void BTN_PremierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PremierActionPerformed
        // TODO add your handling code here:
        try
        {
            Statement stm1 = connBD.getConnection().createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rst = stm1.executeQuery(sql1);
            if (rst.first())
            {
                TB_ID.setText (((Integer)rst.getInt(1)).toString());
                TB_NomItem.setText(rst.getString(2));
                TB_Prix.setText(((Double)rst.getDouble(3)).toString());
                TB_Quantite.setText(((Integer)rst.getInt(4)).toString());
                TB_Efficacite.setText(((Integer)rst.getInt(5)).toString());
                TB_Degats.setText(((Integer)rst.getInt(6)).toString());
                if(rst.getInt(7) == 1)
                {
                    CHK_Dispo.setSelected(true);
                }
                else
                    CHK_Dispo.setSelected(false);
            }
        }
        catch(SQLException se)
        {
            System.out.println(se);
        }
    }//GEN-LAST:event_BTN_PremierActionPerformed
    
    private void BTN_PrecedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PrecedentActionPerformed
        // TODO add your handling code here:
        try
        {
            if (rst.previous())
            {
                TB_ID.setText (((Integer)rst.getInt(1)).toString());
                TB_NomItem.setText(rst.getString(2));
                TB_Prix.setText(((Double)rst.getDouble(3)).toString());
                TB_Quantite.setText(((Integer)rst.getInt(4)).toString());
                TB_Efficacite.setText(((Integer)rst.getInt(5)).toString());
                TB_Degats.setText(((Integer)rst.getInt(6)).toString());
                if(rst.getInt(7) == 1)
                {
                    CHK_Dispo.setSelected(true);
                }
                else
                    CHK_Dispo.setSelected(false);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Précedent impossible");
            }
            
        }
        
        catch(SQLException se)
        {
            JOptionPane.showMessageDialog(this, "précedent impossible");
        }
    }//GEN-LAST:event_BTN_PrecedentActionPerformed
    
    private void BTN_SuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SuivantActionPerformed
        // TODO add your handling code here:
        try
        {
            if(rst.next())
            {
                TB_ID.setText (((Integer)rst.getInt(1)).toString());
                TB_NomItem.setText(rst.getString(2));
                TB_Prix.setText(((Double)rst.getDouble(3)).toString());
                TB_Quantite.setText(((Integer)rst.getInt(4)).toString());
                TB_Efficacite.setText(((Integer)rst.getInt(5)).toString());
                TB_Degats.setText(((Integer)rst.getInt(6)).toString());
                if(rst.getInt(7) == 1)
                {
                    CHK_Dispo.setSelected(true);
                }
                else
                    CHK_Dispo.setSelected(false);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "suivant impossible");
            }
        }
        catch(SQLException se)
        {
            JOptionPane.showMessageDialog(this, "Suivant imposible");
            
        }
    }//GEN-LAST:event_BTN_SuivantActionPerformed
    
    private void BTN_DernierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_DernierActionPerformed
        try
        {
            if(rst.last())
            {
                TB_ID.setText (((Integer)rst.getInt(1)).toString());
                TB_NomItem.setText(rst.getString(2));
                TB_Prix.setText(((Double)rst.getDouble(3)).toString());
                TB_Quantite.setText(((Integer)rst.getInt(4)).toString());
                TB_Efficacite.setText(((Integer)rst.getInt(5)).toString());
                TB_Degats.setText(((Integer)rst.getInt(6)).toString());
                if(rst.getInt(7) == 1)
                {
                    CHK_Dispo.setSelected(true);
                }
                else
                    CHK_Dispo.setSelected(false);
            }   
        } 
        catch(SQLException se)
        {
            JOptionPane.showMessageDialog(this, "dernier imposible");
            
        }
    }//GEN-LAST:event_BTN_DernierActionPerformed
    
    private void BTN_ViderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ViderActionPerformed
        // TODO add your handling code here:
        TB_ID.setText("");
        TB_NomItem.setText("");
        TB_Prix.setText("");
        TB_Quantite.setText("");
        TB_Efficacite.setText("");
        TB_Degats.setText("");
        CHK_Dispo.setSelected(false);
    }//GEN-LAST:event_BTN_ViderActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Arme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Arme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Arme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Arme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Arme().setVisible(true);
            }
        });
    }
// Declaration d'une variable connBD de type ConnectionOracle
    private ConnectionOracle connBD;
    ResultSet rst ;
    String sql1 = "Select I.IDITEM,I.nomItem,I.Prix,I.QuantiteDispo,A.efficacite,A.degats,I.Disponible from Items I inner join Armes A on I.IDITEM=A.IDITEM";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Ajouter;
    private javax.swing.JButton BTN_Dernier;
    private javax.swing.JButton BTN_Modifier;
    private javax.swing.JButton BTN_OK;
    private javax.swing.JButton BTN_Precedent;
    private javax.swing.JButton BTN_Premier;
    private javax.swing.JButton BTN_Suivant;
    private javax.swing.JButton BTN_Supprimer;
    private javax.swing.JButton BTN_Vider;
    private javax.swing.JCheckBox CHK_Dispo;
    private javax.swing.JLabel L_Genre;
    private javax.swing.JTextField TB_Degats;
    private javax.swing.JTextField TB_Efficacite;
    private javax.swing.JTextField TB_ID;
    private javax.swing.JTextField TB_NomItem;
    private javax.swing.JTextField TB_Prix;
    private javax.swing.JTextField TB_Quantite;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
